### ISSUE TITLE
Kernel versions on README.md looks same

### ISSUE THREAD

**Issue by LanderU** [razr/RTWG#1]
Hi @razr, 

on your readme.md the output before/after the kernel patch with PREEMPT_RT looks the same except of the date.

Before reboot output:

> Linux ubuntu 5.4.0-1013-raspi #13 SMP Sat Jul 16 21:00:11 CEST 2020 aarch64 aarch64 aarch64 GNU/Linux

After install the kernel and reboot:

> Linux ubuntu 5.4.0-1013-raspi #13 SMP Sat Jul 18 22:05:32 CEST 2020 aarch64 aarch64 aarch64 GNU/Linux

I assume that the output after restart should be something like

> Linux ubuntu 5.4.0-1013-raspi #13 SMP PPREEMPT_RT Sat Jul 18 22:05:32 CEST 2020 aarch64 aarch64 aarch64 GNU/Linux

Is this a mistake? Or am I missing something?

Thanks in advance!

**Comment by razr** [comment]
Hi @LanderU, I'll update a README shortly, please follow the instructions inside the Dockerfile to build an RT kernel. Let me know if something is missing.

**Comment by razr** [comment]
I have updated README.md and pushed it. Please let me know whether it works for you.

**Comment by LanderU** [comment]
@razr, wow, really fast! LGTM! I'm testing the dockerfiles etc, I'll let you know if I found something to be improved. Thanks again!

**Comment by razr** [comment]
@LanderU thanks much for looking into it
